name: generate git graph

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ ]
  schedule:
    - cron: "5 7 * * */2" # every two days at 7:05am UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch: # run workflow on api request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone remote repo
        run: git clone https://codeberg.org/Starfish/TinyWeatherForecastGermany.git TinyWeatherForecastGermany
          
      - name: clone this repo
        run: git clone https://github.com/${{ github.repository }}.git git-graph
      
      - name: update packages
        run: sudo apt-get update && sudo apt-get upgrade
      
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
    
      - name: install virtualenv
        run: pip install virtualenv
      
      - name: init virtualenv
        run: virtualenv venv
      
      - name: activate virtualenv
        run: source venv/bin/activate

      - name: upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: install graphviz
        run: sudo apt-get install -y graphviz

      - name: list directory contents
        run: ls -lisha

      - name: install pip dependencies
        run: pip install -r git-graph/requirements.txt

      - name: generate git graph using Python and graphviz
        run: python git-graph/git_log2graphviz.py
      
      - name: list directory contents
        run: ls -lisha
      
      - name: archive generated svg
        uses: actions/upload-artifact@v2
        with:
          name: generated-svg
          path: |
            *.svg
            *.dot
      
      - name: copy artifacts to git repo directory
        run: |
          cp *.svg git-graph/ || true
          cp *.dot git-graph/ || true

      - name: prep git commit
        run: |
         cd git-graph
         git status
         git reset
         git add *.svg
         git add *.dot || true
         git status

      - name: git commit and push
        run: |
          cd git-graph
          git config --local user.name eUgEntOptIc44
          git config --local user.email eUgEntOptIc@outlook.de
          git switch -c pages
          git commit -m "update git graph"
          git remote add github-pages "https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git push -u github-pages
      